# Generated by Django 5.1.15 on 2026-05-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('thumbnail', models.ImageField(upload_to='projects/thumbnails/', verbose_name='Miniatura')),
                ('category', models.CharField(choices=[('design', 'Design'), ('web', 'Web')], default='web', max_length=10, verbose_name='Categoria')),
                ('link_url', models.URLField(max_length=500, verbose_name='Link do Projeto')),
                ('github_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='GitHub')),
                ('technologies', models.CharField(help_text='Separadas por vírgula. Ex: Django, React, Figma', max_length=300, verbose_name='Tecnologias')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
    ]
